name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  unit:
    strategy:
      matrix:
        go: [ '1.21', '1.22', '1.23' ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: Test
        run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.go == '1.23'
        with:
          files: coverage.txt
